spring:
  application:
    name: analyzer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: admin
jpa:
  properties:
    hibernate:
     dialect=org:
       hibernate:
        dialect:
         PostgreSQLDialect:


kafka:
      hub-consumer-properties:
        "bootstrap.servers": localhost:9092
        "group.id": analyzer-hub-group
        "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
        "value.deserializer": ru.yandex.practicum.deserializer.HubEventDeserializer
      snapshot-consumer-properties:
        "bootstrap.servers": localhost:9092
        "group.id": analyzer-snapshot-group
        "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
        "value.deserializer": ru.yandex.practicum.deserializer.SensorSnapshotDeserializer
      topics:
         hubs-events: telemetry.hubs.v1
         sensors-snapshot: telemetry.snapshots.v1

grpc:
     client:
       hub-router:
         address: 'static://localhost:59090'
         enableKeepAlive: true
         keepAliveWithoutCalls: true
         negotiationType: plaintext